# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - { "old": "etherpad_container_image_name_prefix", "new": "etherpad_container_image_registry_prefix" }
    - { "old": "etherpad_container_src_path", "new": "etherpad_container_image_self_build_src_files_path" }

- name: Fail if required Etherpad settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - etherpad_hostname
    - etherpad_path_prefix
    - etherpad_database_hostname
    - etherpad_container_network

- name: Run if Traefik is enabled
  when: etherpad_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required ntfy Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - etherpad_container_labels_traefik_hostname
        - etherpad_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `etherpad_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if etherpad_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          etherpad_container_labels_traefik_path_prefix (`{{ etherpad_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/etherpad`).
      when: "etherpad_container_labels_traefik_path_prefix != '/' and etherpad_container_labels_traefik_path_prefix[-1] == '/'"
